# Generated by Django 3.2.5 on 2023-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=45)),
                ('course_credit', models.DecimalField(decimal_places=2, max_digits=3, max_length=10, verbose_name='Course Credit: ')),
                ('ct_full_marks', models.DecimalField(decimal_places=2, max_digits=3, max_length=10)),
                ('att_full_marks', models.DecimalField(decimal_places=2, max_digits=3, max_length=10)),
                ('final_full_marks', models.DecimalField(decimal_places=2, max_digits=3, max_length=10)),
            ],
        ),
    ]
