# Generated by Django 3.2.5 on 2023-01-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='att_full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=10, verbose_name='Course Credit: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='ct_full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=10),
        ),
    ]
