# Generated by Django 3.2.5 on 2023-01-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.PositiveSmallIntegerField()),
                ('st_name', models.CharField(max_length=25)),
                ('st_dob', models.DateField()),
                ('st_dist', models.CharField(max_length=15)),
                ('st_phone', models.CharField(max_length=11)),
                ('st_mail', models.EmailField(max_length=254)),
                ('pg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.program')),
            ],
        ),
    ]
